// Bump the project version in every file that has its own copy.
//
// Usage:
//   pnpm sync-version 1.0.1
//
// Updates:
//   package.json                                   -> "version"
//   src-tauri/tauri.conf.json                      -> "version"
//   src-tauri/gen/android/app/tauri.properties     -> versionName + versionCode
//                                                     (skipped if the file is
//                                                      missing - it is
//                                                      regenerated by Tauri on
//                                                      the next android build)
//
// versionCode follows Tauri's own semver-derived formula so local Android
// builds match what CI produces from a clean checkout:
//   versionCode = major * 1_000_000 + minor * 1_000 + patch

import { existsSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")

const version = process.argv[2]
if (!version || !/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) {
  console.error(`Usage: pnpm sync-version <x.y.z[-prerelease]>`)
  console.error(`Got: ${process.argv[2] ?? "(nothing)"}`)
  process.exit(1)
}

const pkgPath = path.join(ROOT, "package.json")
const tauriConfPath = path.join(ROOT, "src-tauri", "tauri.conf.json")
const androidPath = path.join(ROOT, "src-tauri", "gen", "android", "app", "tauri.properties")

patchJsonVersion(pkgPath, "package.json")
patchJsonVersion(tauriConfPath, "src-tauri/tauri.conf.json")

const [major, minor, patch] = version.split("-")[0].split(".").map(Number)
const versionCode = major * 1_000_000 + minor * 1_000 + patch

if (existsSync(androidPath)) {
  const raw = readFileSync(androidPath, "utf8")
  if (!/tauri\.android\.versionCode=\d+/.test(raw) || !/tauri\.android\.versionName=/.test(raw)) {
    console.error(`Could not find versionName/versionCode in ${androidPath}`)
    process.exit(1)
  }
  const patched = raw
    .replace(/tauri\.android\.versionName=[^\r\n]*/, `tauri.android.versionName=${version}`)
    .replace(/tauri\.android\.versionCode=\d+/, `tauri.android.versionCode=${versionCode}`)
  writeFileSync(androidPath, patched)
  console.log(`src-tauri/gen/android/app/tauri.properties -> ${version} (versionCode ${versionCode})`)
} else {
  console.log(`src-tauri/gen/android/app/tauri.properties: not found, skipping`)
  console.log(`  (Tauri will regenerate it on the next \`pnpm tauri:android\` build,`)
  console.log(`   using versionCode ${versionCode} derived from tauri.conf.json)`)
}

function patchJsonVersion(file, label) {
  const raw = readFileSync(file, "utf8")
  if (!/"version"\s*:\s*"\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?"/.test(raw)) {
    console.error(`Could not find a "version": "x.y.z" line in ${file}`)
    process.exit(1)
  }
  const patched = raw.replace(
    /("version"\s*:\s*")\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(")/,
    `$1${version}$2`,
  )
  writeFileSync(file, patched)
  console.log(`${label} -> ${version}`)
}
