// Builds the "diagnostic ZIP" a user attaches to a GitHub issue: environment, network
// log, credential-free playlist summary, last diagnostic run, and redacted log tails.

import { createZip } from "@/scripts/lib/zip-writer.js"
import { getNetworkLog } from "@/scripts/lib/net-log.js"
import { redactUrl } from "@/scripts/lib/log.js"
import { getEntries, getActiveEntry } from "@/scripts/lib/creds.js"
import { sanitizeFilename } from "@/scripts/lib/format.js"

type UnknownRecord = Record<string, unknown>

function isRecord(value: unknown): value is UnknownRecord {
  return value !== null && typeof value === "object" && !Array.isArray(value)
}

export interface PlaylistEntrySummary {
  index: number
  type: string
  isActive: boolean
  hasMirrors: boolean
  mirrorCount: number
  liveContainer: string | null
  hasEpgOverride: boolean
  additionalEpgUrlCount: number
  providerEpgDisabled: boolean
  hasStreamHeaders: boolean
}

export interface PlaylistSummary {
  count: number
  activeIndex: number
  entries: PlaylistEntrySummary[]
}

// Allowlist only: read type/mirrors/liveContainer/epgUrl shape flags off an entry,
// never its host/url/username/password. Never spread the source entry.
function summarizeEntry(entry: unknown, index: number, isActive: boolean): PlaylistEntrySummary {
  const record = isRecord(entry) ? entry : {}
  const mirrors = Array.isArray(record.mirrors) ? record.mirrors : []
  const additionalEpgUrls = Array.isArray(record.additionalEpgUrls) ? record.additionalEpgUrls : []
  const streamHeaders = isRecord(record.streamHeaders) ? record.streamHeaders : null

  return {
    index,
    type: typeof record.type === "string" ? record.type : "unknown",
    isActive,
    hasMirrors: mirrors.length > 0,
    mirrorCount: mirrors.length,
    liveContainer: typeof record.liveContainer === "string" ? record.liveContainer : null,
    hasEpgOverride: typeof record.epgUrl === "string" && record.epgUrl.trim().length > 0,
    additionalEpgUrlCount: additionalEpgUrls.length,
    providerEpgDisabled: !!record.disableProviderEpg,
    hasStreamHeaders: streamHeaders != null && Object.keys(streamHeaders).length > 0,
  }
}

export function summarizePlaylists(entries: unknown[], activeId: string | null): PlaylistSummary {
  const list = Array.isArray(entries) ? entries : []
  const activeIndex =
    typeof activeId === "string" && activeId
      ? list.findIndex((entry) => isRecord(entry) && entry._id === activeId)
      : -1

  return {
    count: list.length,
    activeIndex,
    entries: list.map((entry, index) => summarizeEntry(entry, index, index === activeIndex)),
  }
}

export interface BundleInput {
  createdAt: Date
  snapshot: unknown
  networkLog: unknown
  playlists: PlaylistSummary
  diagnosticResult: unknown | null
  logFiles: { name: string; text: string }[]
}

function buildReadme(input: BundleInput): string {
  const lines = [
    "Extreme InfiniTV diagnostic bundle",
    "",
    "This archive was generated by the app for a bug report. Usernames, passwords",
    "and tokens are stripped before these files are written; the playlist summary",
    "carries no host or URL at all. The network log and the app logs can still",
    "show the server names the app contacted, so review them before you attach",
    "this zip to a public GitHub issue.",
    "",
    `Created: ${input.createdAt.toISOString()}`,
    "",
    "Files included:",
    "- snapshot.json: app version, platform, and playback capability flags.",
    "- network-log.json: recent provider network requests, redacted.",
    "- playlist-summary.json: playlist types and counts, no hosts or credentials.",
  ]
  if (input.diagnosticResult != null) {
    lines.push("- diagnostic-result.json: the most recent connection diagnostic run.")
  }
  for (const logFile of input.logFiles) {
    lines.push(`- logs/${logFile.name}: tail of the app log file, redacted.`)
  }
  return lines.join("\n")
}

function toRedactedJson(value: unknown): string {
  return redactUrl(JSON.stringify(value, null, 2))
}

export function buildBundleManifest(input: BundleInput): { name: string; text: string }[] {
  const files: { name: string; text: string }[] = []
  files.push({ name: "README.txt", text: buildReadme(input) })
  files.push({ name: "snapshot.json", text: toRedactedJson(input.snapshot) })
  files.push({ name: "network-log.json", text: toRedactedJson(input.networkLog) })
  files.push({ name: "playlist-summary.json", text: toRedactedJson(input.playlists) })
  if (input.diagnosticResult != null) {
    files.push({ name: "diagnostic-result.json", text: toRedactedJson(input.diagnosticResult) })
  }
  for (const logFile of input.logFiles) {
    files.push({ name: `logs/${logFile.name}`, text: redactUrl(logFile.text) })
  }
  return files
}

export function suggestedBundleFilename(appVersion: string | null, createdAt: Date): string {
  const version = appVersion && appVersion.trim() ? appVersion.trim() : "unknown"
  const pad = (value: number) => String(value).padStart(2, "0")
  const stamp =
    `${createdAt.getFullYear()}${pad(createdAt.getMonth() + 1)}${pad(createdAt.getDate())}` +
    `-${pad(createdAt.getHours())}${pad(createdAt.getMinutes())}`
  return sanitizeFilename(`extreme-infinitv-diagnostics-${version}-${stamp}.zip`)
}

export function recentLogFileNames(now: Date, days: number): string[] {
  const count = Math.max(0, Math.floor(days))
  const pad = (value: number) => String(value).padStart(2, "0")
  const names: string[] = []
  for (let offset = 0; offset < count; offset++) {
    const date = new Date(now.getFullYear(), now.getMonth(), now.getDate() - offset)
    names.push(`app-${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}.log`)
  }
  return names
}

export function tailLogBytes(bytes: Uint8Array, maxBytes: number): Uint8Array {
  if (bytes.length <= maxBytes) return bytes
  return bytes.subarray(bytes.length - maxBytes)
}

// `truncated` tells us the leading bytes may be a cut multibyte/partial-line
// record; drop through the first newline so the kept text never starts mid-record.
export function decodeLogTail(bytes: Uint8Array, truncated: boolean): string {
  const text = new TextDecoder("utf-8", { fatal: false }).decode(bytes)
  if (!truncated) return text
  const newlineIndex = text.indexOf("\n")
  return newlineIndex === -1 ? "" : text.slice(newlineIndex + 1)
}

export interface CollectedBundle {
  filename: string
  bytes: Uint8Array
  fileNames: string[]
}

async function safeAsync<Value>(probe: () => Promise<Value>, fallback: Value): Promise<Value> {
  try {
    return await probe()
  } catch {
    return fallback
  }
}

// Races `promise` against a timer so a step that never settles can't hang the export.
export function withTimeout<Value>(promise: Promise<Value>, ms: number, fallback: Value): Promise<Value> {
  return new Promise((resolve) => {
    const timer = setTimeout(() => resolve(fallback), ms)
    promise.then(
      (value) => {
        clearTimeout(timer)
        resolve(value)
      },
      () => {
        clearTimeout(timer)
        resolve(fallback)
      }
    )
  })
}

const SNAPSHOT_TIMEOUT_MS = 5000
const LOG_TAILS_TIMEOUT_MS = 5000
const NETWORK_LOG_TIMEOUT_MS = 2000
const PLAYLISTS_TIMEOUT_MS = 2000
const DIAGNOSTIC_RESULT_TIMEOUT_MS = 2000

function detectIsTauriRuntime(): boolean {
  return (
    typeof window !== "undefined" &&
    (!!(window as any).__TAURI_INTERNALS__ || !!(window as any).__TAURI__)
  )
}

function detectIsAndroidRuntime(): boolean {
  return typeof navigator !== "undefined" && /Android/i.test(navigator.userAgent || "")
}

const LOG_FILE_NAME_PATTERN = /^app-\d{4}-\d{2}-\d{2}\.log$/
const LOG_TAIL_MAX_BYTES = 512 * 1024
const RECENT_LOG_FILE_COUNT = 2

async function tailOf(bytes: Uint8Array): Promise<string> {
  const truncated = bytes.length > LOG_TAIL_MAX_BYTES
  return decodeLogTail(tailLogBytes(bytes, LOG_TAIL_MAX_BYTES), truncated)
}

// Directory enumeration is allowed here (fs:allow-read-dir on desktop, denied on Android).
async function readDesktopLogTails(): Promise<{ name: string; text: string }[]> {
  const { appLogDir, join } = await import("@tauri-apps/api/path")
  const { readDir, readFile } = await import("@tauri-apps/plugin-fs")
  const logDir = await appLogDir()
  const dirEntries = await readDir(logDir)
  const candidateNames = dirEntries
    .map((entry) => entry.name)
    .filter((name): name is string => typeof name === "string" && LOG_FILE_NAME_PATTERN.test(name))
    .sort()
    .reverse()
    .slice(0, RECENT_LOG_FILE_COUNT)

  const tails: { name: string; text: string }[] = []
  for (const name of candidateNames) {
    try {
      const bytes = await readFile(await join(logDir, name))
      tails.push({ name, text: await tailOf(bytes) })
    } catch {
      /* one unreadable log file shouldn't drop the rest */
    }
  }
  return tails
}

// No directory listing on Android - probe the candidate names one by one instead.
async function readAndroidLogTails(): Promise<{ name: string; text: string }[]> {
  const { appLogDir, join } = await import("@tauri-apps/api/path")
  const { readFile, exists } = await import("@tauri-apps/plugin-fs")
  const logDir = await appLogDir()

  const tails: { name: string; text: string }[] = []
  for (const name of recentLogFileNames(new Date(), RECENT_LOG_FILE_COUNT)) {
    try {
      const path = await join(logDir, name)
      if (!(await exists(path))) continue
      const bytes = await readFile(path)
      tails.push({ name, text: await tailOf(bytes) })
    } catch {
      /* one missing/unreadable candidate shouldn't drop the rest */
    }
  }
  return tails
}

async function readRecentLogTails(): Promise<{ name: string; text: string }[]> {
  if (!detectIsTauriRuntime()) return []
  if (detectIsAndroidRuntime()) return readAndroidLogTails()
  return readDesktopLogTails()
}

export async function collectDiagnosticBundle(): Promise<CollectedBundle> {
  const createdAt = new Date()

  const [snapshot, networkLog, playlists, diagnosticResult, logFiles] = await Promise.all([
    withTimeout(
      safeAsync<unknown>(async () => {
        const { collectSessionSnapshot } = await import("@/scripts/lib/diagnostic-snapshot.js")
        return await collectSessionSnapshot()
      }, null),
      SNAPSHOT_TIMEOUT_MS,
      null
    ),
    withTimeout(
      safeAsync<unknown>(async () => getNetworkLog(), null),
      NETWORK_LOG_TIMEOUT_MS,
      null
    ),
    withTimeout(
      safeAsync<PlaylistSummary>(async () => {
        const entries = await getEntries()
        const activeEntry = await getActiveEntry()
        const activeId = isRecord(activeEntry) && typeof activeEntry._id === "string" ? activeEntry._id : null
        return summarizePlaylists(Array.isArray(entries) ? entries : [], activeId)
      }, { count: 0, activeIndex: -1, entries: [] }),
      PLAYLISTS_TIMEOUT_MS,
      { count: 0, activeIndex: -1, entries: [] }
    ),
    withTimeout(
      safeAsync<unknown>(async () => {
        const { getLastDiagnosticResult } = await import("@/scripts/lib/diagnostic.js")
        return getLastDiagnosticResult()
      }, null),
      DIAGNOSTIC_RESULT_TIMEOUT_MS,
      null
    ),
    withTimeout(
      safeAsync<{ name: string; text: string }[]>(() => readRecentLogTails(), []),
      LOG_TAILS_TIMEOUT_MS,
      []
    ),
  ])

  const manifest = buildBundleManifest({ createdAt, snapshot, networkLog, playlists, diagnosticResult, logFiles })
  const textEncoder = new TextEncoder()
  const bytes = createZip(
    manifest.map((file) => ({ name: file.name, data: textEncoder.encode(file.text), modifiedAt: createdAt }))
  )

  const appVersion = isRecord(snapshot) && typeof snapshot.appVersion === "string" ? snapshot.appVersion : null

  return {
    filename: suggestedBundleFilename(appVersion, createdAt),
    bytes,
    fileNames: manifest.map((file) => file.name),
  }
}
